PKGS:
 - nethack36
 - gnome3-lite
 - zsh
 - emacs
 - vim
 - chromium
 - nvidia-driver
 - mongodb
CUSTOM:
 ~/.shrc : /root/.shrc
 ~/.bashrc : /root/.bashrc
 ~/.zshrc : /root/.zshrc
 ~/.emacs.d : /root/.emacs.d
 ~/.vimrc : /root/.vimrc
