#! /bin/sh

# a very user specific script to run a freebsd vm
# you'll definitely have to change this depending on your system
# for the original commands check out the handbook (bhyve section)

# Austin Shafer - 2017

USER=ashafer

# print and run the command given
cmd() {
      echo "$@"
      "$@"
}

cmd sh /usr/share/examples/bhyve/vmrun.sh -c 1 -m 1024M -t tap0 -d ~${USER}/hyve/bsdguest/custom-bsd.img bsdguest
